name: Run pytest

on: push

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Set up Python 3.7
              uses: actions/setup-python@v2
              with:
                  python-version: 3.7
            - uses: dschep/install-pipenv-action@v1
            - name: Install dependencies
              run: |
                  pipenv install
            - name: Test with pytest
              run: |
                  chmod +x 01_hello/solutions/hello.py
                  pipenv run pytest -xv 01_hello/test.py
            - name: decrypt
              run: |
                  chmod +x src/decrypt.py
                  pipenv run python src/decrypt.py -k ${{ secrets.SOLUTIONS_KEY }}
                  cat 01_hello/solutions/hello_test.py

# ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
